[package]
name = "coolprop-sys"
version = "0.1.0-alpha"
authors = ["Vladimir Portyanikhin <v.portyanikhin@ya.ru>"]
edition = "2021"
description = "FFI bindings to CoolProp"
readme = "README.md"
homepage = "https://github.com/portyanikhin/fluids-rs"
repository = "https://github.com/portyanikhin/fluids-rs"
license = "MIT"
keywords = ["CoolProp", "ffi", "bindings"]
categories = ["api-bindings", "science"]

[dependencies]
